/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        screens: {
            sm: "500px",
            smmd: "678px",
            md: "768px",
            lg: "976px",
            xl: "1440px",
        },
        extend: {
            spacing: {
                18: "70px",
                50: "200px",
                500: "572px",
                23: "123px",
                154: "154px",
                143: "143px",
                "9/10": "90%",
                400: "400px",
            },
            colors: {
                pink: "#D52358",
                gray: "#BBBBBB",
                gray2: "#6C6C6C",
                gray3: "#B6B2B2",
                gray4: "#575757",
                gray5: "#B8B8B8",
                purple: "#8C6FDE",
                "light-purple": "#AF9CE2",
                "dark-purple": "#502BB8",
                "light-black": "#2F2F2F",
                "light-black2": "#3F3F3F",
                black: "#000000",
                black2: "#1A1A1A",
                black3: "#2F2F2F",
                "black-trans": "rgba(0, 0, 0, 0.5)",
                pink2: "#D42358",
                "light-green": "#7D9683",
                green: "#3A5040",
                yellow: "#B1BB77",
                "dark-yellow": "#666F36",
                "light-blue": "#798EBA",
                blue: "#264178",
                "light-pink": "#E1658A",
            },
            fontFamily: {
                Inter: ["Inter", "sans-serif"],
                Poppins: ["Poppins", "sans-serif"],
                Helve: ["Helvetica Neue", "sans-serif"],
            },
            fontSize: {
                md2: "20px",
                32: "32px",
            },
            borderRadius: {
                6: "6px",
                10: "10px",
                9: "9px",
            },
            lineHeight: {
                24: "24px",
                19: "19px",
                38: "38px",
                48: "48px",
            },
            minWidth: {
                120: "120px",
            },
        },
    },
    plugins: [],
};
